services:
    classmapperservice:
        class: 'Core\ClassMapperBundle\Service\ClassMapper'
        arguments: ["@service_container",%objectMapper%]
        
    eventlistener.classmapper:
      class: 'Core\ClassMapperBundle\EventListener\ClassMapperListener'
      arguments: [@service_container]
      tags:
         - { name: kernel.event_listener, priority: 61, event: kernel.controller, method: onKernelController}
                  
